services:
  backend-react:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend-react
    restart: unless-stopped